### ISSUE TITLE
Dependency conflict with Python 3.12 

### ISSUE THREAD

**Issue by akashshah59** [stripe-interview/ml-python-interview-prep#1]
The dependencies 

requests==2.22.0 
six== 1.12.0 

seem to have a conflict for python 3.12. It is due to changes in the urllib3 library that seems to import six differently from previous versions

Solution: Upgrade urllib3, requests as well as six. Downgrading to Python 3.8.13 also helped. 

<u> Final output using downgraded python version 3.8.13: </u>

Numpy version: 1.24.4
Pandas version: 2.0.3
Pytest version: 8.3.2
Requests version: 2.22.0

**Comment by jasonf7** [comment]
Facing same issue with Python 3.13.5 (both Windows + Mac).
```
(interview_env) D:\ml-python-interview-prep>python verify_requirements.py
Traceback (most recent call last):
  File "D:\ml-python-interview-prep\verify_requirements.py", line 4, in <module>
    import pandas as pd
  File "D:\ml-python-interview-prep\interview_env\Lib\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
    ...<62 lines>...
    )
  File "D:\ml-python-interview-prep\interview_env\Lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
    ...<4 lines>...
    )
  File "D:\ml-python-interview-prep\interview_env\Lib\site-packages\pandas\_libs\__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "D:\ml-python-interview-prep\interview_env\Lib\site-packages\pandas\_libs\tslibs\__init__.py", line 40, in <module>
    from pandas._libs.tslibs.conversion import localize_pydatetime
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timestamps.pyx", line 1, in init pandas._libs.tslibs.timestamps
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1, in init pandas._libs.tslibs.timedeltas
  File "pandas/_libs/tslibs/timezones.pyx", line 24, in init pandas._libs.tslibs.timezones
  File "D:\ml-python-interview-prep\interview_env\Lib\site-packages\dateutil\tz\__init__.py", line 2, in <module>
    from .tz import *
  File "D:\ml-python-interview-prep\interview_env\Lib\site-packages\dateutil\tz\tz.py", line 21, in <module>
    from six.moves import _thread
ModuleNotFoundError: No module named 'six.moves'

(interview_env) D:\ml-python-interview-prep>python verify_requirements.py
Traceback (most recent call last):
  File "D:\ml-python-interview-prep\verify_requirements.py", line 6, in <module>
    import requests
  File "D:\ml-python-interview-prep\interview_env\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "D:\ml-python-interview-prep\interview_env\Lib\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "D:\ml-python-interview-prep\interview_env\Lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
    ...<13 lines>...
    )
  File "D:\ml-python-interview-prep\interview_env\Lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

Fix was to re-install both `six` and `urllib3`
```
pip uninstall six
pip install six
pip uninstall urllib3
pip install urllib3
```

I do get an error but the script runs -- hope it's okay for the interview!
```
(interview_env) D:\ml-python-interview-prep>pip install urllib3
Collecting urllib3
  Using cached urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Using cached urllib3-2.5.0-py3-none-any.whl (129 kB)
Installing collected packages: urllib3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
requests 2.22.0 requires urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you have urllib3 2.5.0 which is incompatible.
Successfully installed urllib3-2.5.0

(interview_env) D:\ml-python-interview-prep>python verify_requirements.py
D:\ml-python-interview-prep\interview_env\Lib\site-packages\requests\__init__.py:89: RequestsDependencyWarning: urllib3 (2.5.0) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Numpy version: 2.3.2
Pandas version: 2.3.1
Pytest version: 8.4.1
Requests version: 2.22.0
```
